name: downloader
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  flutter_insta: ^0.1.5 
  path_provider: any
  lottie: 0.7.0+1
  font_awesome_flutter: ^8.12.0
  url_launcher: ^5.7.10
  image_downloader: ^0.20.1
  permission_handler: ^5.1.0+2
  flutter_downloader: ^1.1.9
  flutter_launcher_icons: any
  flutter_file_manager: ^0.2.0
  persistent_bottom_nav_bar: ^4.0.2
  fluttertoast: ^8.0.8

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/splash_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/

  